name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # إنشاء ملف استثناء مؤقت لمنع رفع الصوت والخطوط نهائياً
          echo "*.m4a" >> .git/info/exclude
          echo "*.ttf" >> .git/info/exclude
          
          # إزالة تتبع الملفات لو كانت متسيفة في الكاش عشان الـ exclude يشتغل مجبر
          git rm --cached -r --ignore-unmatch .
          git add .
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -m "Ignore binaries for HF" --allow-empty
          
          # الرفع الفعلي مجبر إلى Hugging Face
          git remote add hf https://m7mddemo0o:$HF_TOKEN@huggingface.co/spaces/m7mddemo0o/sovereign-bot
          git push --force hf dev:main
